logging:
  level:
    org:
      springframework:
        security: info

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: read:public_repo
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user

  datasource:
    url: jdbc:postgresql://localhost:5432/exambyte_db
    username: exambyte_user
    password: exambyte_password
    driver-class-name: org.postgresql.driver
  jpa:
    hibernate:
      ddl-auto: none # Verhindert die automatische DDL-Ausf√ºhrung
  flyway:
    enabled: true
    locations: classpath:db/migration # Definiert den Speicherort der Migrationsskripte